data:
  - name: "SQ4 Regression CardX Wealth Greenfield"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4-Regression"
    webhook_path: "/macros/s/AKfycbxwZ6VeIoNynbSwAxLcivfJg9UI5wp9NCc0nCfPPXiWH3FMohLUrtDzOHn2GkLthsBY/exec"
    env: "UAT"
  - name: "SQ4 SIT CardX Wealth MFT"
    project_name: "CardX - System Integration Testing"
    version_name: "Wealth Post-Greenfield Jan 2026"
    cycle_name: "SQ4"
    webhook_path: "/macros/s/AKfycbxEoj8z2ok9dMhfd1OTMdHuOTs2AXz7nvh2wqcGd7wvHmrJpfUKl58ad-feu7w3Psw-/exec"
    env: "SIT"