data:
  - name: "SQ4 Regression CardX Wealth Greenfield"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4-Regression"
    webhook_path: "/macros/s/AKfycbxwZ6VeIoNynbSwAxLcivfJg9UI5wp9NCc0nCfPPXiWH3FMohLUrtDzOHn2GkLthsBY/exec"
    env: "UAT"
  - name: "SQ4 UAT CardX Wealth Greenfield"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4"
    webhook_path: "macros/s/AKfycbxZnTGF9YhWHNjlAD_NhmlAYAchyg4e9CAsk0JsPuz_WxKvxUq9e8J2kxLlLbyAUj3mcQ/exec"
    env: "UAT"