data:
  - name: "SQ4 SIT CardX Wealth Greenfield"
    project_name: "CardX - System Integration Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4"
    webhook_path: "/macros/s/AKfycbwZ7G8NsyMYucw03yBMlxkFSCVMKF8pZ-CFz9y3KhTklUIj9f2nI6RDb-rAXM_pFd2_0g/exec"
    env: "SIT"
  - name: "SQ4 UAT CardX Wealth Greenfield"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4"
    webhook_path: "macros/s/AKfycbxZnTGF9YhWHNjlAD_NhmlAYAchyg4e9CAsk0JsPuz_WxKvxUq9e8J2kxLlLbyAUj3mcQ/exec"
    env: "UAT"