data:
  - name: "SQ4 UAT CardX Sep 2025 Regression Mini#2"
    project_name: "CardX - User Acceptance Testing"
    version_name: "Sep 2025"
    cycle_name: "SQ4"
    webhook_path: "/macros/s/AKfycbwVdJh7CKbAcEFt25zjodLRUrowRH7MjdCMTQFCYwZgZogVnKj0wXrw_H7OHJgaW0Vs/exec"
    env: "UAT"
    folders: 
      - "SQ4 - Regression - Mini #2"
