data:
  - name: "SQ4 SIT CardX Wealth Greenfield"
    project_name: "CardX - System Integration Testing"
    version_name: "Wealth Greenfield Nov 2025"
    cycle_name: "SQ4"
    webhook_path: "/macros/s/AKfycbwZ7G8NsyMYucw03yBMlxkFSCVMKF8pZ-CFz9y3KhTklUIj9f2nI6RDb-rAXM_pFd2_0g/exec"
    env: "SIT"
